from __future__ import annotations

import hashlib
import os
import secrets
from typing import Any

from ombrebrain.context.memory_flash import (
    read_memory_flash,
)
from ombrebrain.context.recall_types import (
    LOCK,
    atomic_write,
    is_valid_cognitive_request_id,
    is_valid_conversation_id,
    is_valid_fingerprint,
    is_valid_recall_id,
    now_iso,
    read_json,
    recall_request_dir,
    recall_request_path,
)
from ombrebrain.context.validators.freshness import (
    is_valid_revision,
    validate_context_freshness,
)


# Memory Recall Request v1 — authorization only.
#
# retrieved       != surfaced
# surfaced        != noticed
# noticed         != recall_requested
# recall_requested != memory_loaded
# memory_loaded   != used
# used            != reinforced
#
# This module implements exactly ONE new rung:
#
#     surfaced_as_flash -> recall_requested
#
# A Recall Request is an EXPLICIT, AI-initiated action. It is never
# generated by the Surfacing Policy, by Memory Flash, by the Gateway,
# by the Confidence Gate or by any automatic rule. Nothing in this
# module is ever triggered by a shadow artifact.
#
# It answers one question only: is THIS anchor memory one that was
# truly ``surfaced_as_flash`` for THIS conversation AND THIS
# cognitive request? If not, the request is refused with a
# distinguishing reason. An arbitrary memory id can never be turned
# into a recall target just because it exists in the store.
#
# This module performs no retrieval, loads no memory content and calls
# no model. Authorization reads exactly one Flash artifact (the
# request-local one) and never mutates anything; the optional
# persistence below records the AI's own Recall action as an
# independent request event, so
#
#     recall_requested = YES
#     memory_loaded    = ZERO
#
# is a representable state: a Recall Request that was explicitly made
# and then could not be satisfied is still a real Recall Request.
# Persisting the event never reinforces a memory and never writes a
# memory source file.

_VERSION = "memory-recall-request.v1"

# Public contract name: the Recall Request artifact version. The
# Related Recall module validates a recall request against this, so
# the two modules can never drift apart.
RECALL_REQUEST_VERSION = _VERSION

# Live model-triggered recall is NOT wired in this phase, so the mode
# stays honest: the control plane is verified internally only.
_MODE = "shadow_only"

# The only scope implemented in v1. ``full`` is deliberately NOT
# implemented: this phase never dumps an unbounded memory set.
_ALLOWED_SCOPE = "related"

# Initial (and, in this phase, only) Recall Request status: the AI
# asked for this recall. Whether memories can be loaded afterwards is
# a separate fact recorded by the Usage Signal.
_STATUS_REQUESTED = "requested"

_ENV_RECALL_ENABLED = (
    "OMBRE_GATEWAY_CONTEXT_RECALL_ENABLED"
)
_ENV_RELATED_RECALL_SHADOW = (
    "OMBRE_GATEWAY_CONTEXT_RELATED_RECALL_SHADOW"
)

_FLASH_VERSION = "memory-flash.v1"
_FLASH_MODE = "shadow_only"

# Refusal reasons. Each one is a distinct, structural fact; none of
# them is "the id exists so give it to the model".
_REASON_INVALID = "invalid_request"
_REASON_DISABLED = "recall_disabled"
_REASON_FLASH_NOT_FOUND = "flash_not_found"
_REASON_FLASH_IDENTITY = "flash_identity_mismatch"
_REASON_ANCHOR_NOT_SURFACED = "anchor_not_surfaced"
_REASON_SOURCE_REVISION = "source_revision_mismatch"
_REASON_INVALID_SCOPE = "invalid_requested_scope"


def _truthy(value: Any) -> bool:
    return str(value or "").strip().lower() in (
        "1",
        "true",
        "yes",
        "on",
    )


def recall_control_plane_enabled() -> bool:
    """Is the Recall control plane allowed to serve a request at all?

    Default OFF. Either the live master switch
    (``OMBRE_GATEWAY_CONTEXT_RECALL_ENABLED``) or the internal shadow
    switch (``OMBRE_GATEWAY_CONTEXT_RELATED_RECALL_SHADOW``) may
    enable it, so an operator can verify the control plane end to end
    (SHADOW=1, ENABLED=0) without pretending the model can trigger a
    live recall.
    """

    return _truthy(
        os.environ.get(_ENV_RECALL_ENABLED)
    ) or _truthy(
        os.environ.get(
            _ENV_RELATED_RECALL_SHADOW
        )
    )


def new_recall_id() -> str:
    """One unique id per Recall Request. Never time-based."""

    return "recall_" + secrets.token_hex(16)


def recall_request_fingerprint(
    *,
    conversation_id: str,
    cognitive_request_id: str,
    anchor_memory_id: str,
    requested_scope: str,
) -> str:
    """Deterministic identity of one recall request.

    ``conversation_id + cognitive_request_id + anchor + scope``: the
    same retried request folds onto the same fingerprint, while two
    different anchors in one request (or the same anchor in two
    requests) stay distinct. Only a digest is returned.
    """

    payload = "\0".join(
        [
            str(conversation_id or ""),
            str(cognitive_request_id or ""),
            str(anchor_memory_id or ""),
            str(requested_scope or ""),
        ]
    )

    return hashlib.sha256(
        payload.encode("utf-8")
    ).hexdigest()


def _surfaced_memory_ids(
    flash: Any,
) -> list[str]:
    if not isinstance(flash, dict):
        return []

    flashes = flash.get("flashes")

    if not isinstance(flashes, list):
        return []

    ids: list[str] = []

    for item in flashes:
        if not isinstance(item, dict):
            continue

        memory_id = item.get("memory_id")

        if (
            isinstance(memory_id, str)
            and memory_id.strip()
        ):
            ids.append(memory_id.strip())

    return ids


def _refuse(
    reason: str,
    *,
    mode: str = _MODE,
) -> dict[str, Any]:
    return {
        "valid": False,
        "mode": mode,
        "reason": reason,
        "recall_request": None,
        "flash": None,
    }


def authorize_recall_request(
    *,
    conversation_id: Any,
    cognitive_request_id: Any,
    anchor_memory_id: Any,
    requested_scope: Any = _ALLOWED_SCOPE,
    source_flash_unified_revision: Any = None,
) -> dict[str, Any]:
    """Validate one explicit Recall Request against the real Flash.

    Pure and read-only; it never raises for a refused request. The
    validation chain is exactly:

        conversation_id
          + cognitive_request_id
            + Memory Flash artifact of THIS request
              + anchor_memory_id in flash.flashes[].memory_id
                + the Flash's own source_unified_revision

    ``source_flash_unified_revision`` is optional: when the trusted
    caller does not pin a revision, the Flash's own revision is used,
    so the binding is still enforced structurally. When it IS pinned,
    a mismatch is refused.

    The trusted caller (Gateway / Coordinator) binds conversation_id
    and cognitive_request_id. The model may only ever name an anchor;
    it can never choose the conversation, the request or a scope
    other than ``related``.
    """

    if not recall_control_plane_enabled():
        return _refuse(_REASON_DISABLED)

    if not is_valid_conversation_id(
        conversation_id
    ):
        return _refuse(_REASON_INVALID)

    if not is_valid_cognitive_request_id(
        cognitive_request_id
    ):
        return _refuse(_REASON_INVALID)

    if (
        not isinstance(anchor_memory_id, str)
        or not anchor_memory_id.strip()
    ):
        return _refuse(_REASON_INVALID)

    if requested_scope != _ALLOWED_SCOPE:
        return _refuse(_REASON_INVALID_SCOPE)

    anchor = anchor_memory_id.strip()

    flash = read_memory_flash(
        conversation_id=conversation_id,
        cognitive_request_id=(
            cognitive_request_id
        ),
    )

    if flash is None:
        return _refuse(_REASON_FLASH_NOT_FOUND)

    # Structural identity of the Flash artifact: the right contract,
    # the right conversation AND the right request. A Flash belonging
    # to another request or conversation can never authorize a recall
    # here, even if its revision number happens to match.
    if (
        flash.get("version") != _FLASH_VERSION
        or flash.get("mode") != _FLASH_MODE
    ):
        return _refuse(_REASON_FLASH_IDENTITY)

    if (
        flash.get("conversation_id")
        != conversation_id
        or flash.get(
            "cognitive_request_id"
        )
        != cognitive_request_id
    ):
        return _refuse(_REASON_FLASH_IDENTITY)

    if (
        flash.get("decision") != "surfaced"
    ):
        return _refuse(_REASON_FLASH_NOT_FOUND)

    flash_revision = flash.get(
        "source_unified_revision"
    )

    if source_flash_unified_revision is None:
        expected_revision = flash_revision
    else:
        expected_revision = (
            source_flash_unified_revision
        )

    freshness = validate_context_freshness(
        checked_revision=flash_revision,
        expected_revision=expected_revision,
        invalid_reason=_REASON_SOURCE_REVISION,
        mismatch_reason=(
            _REASON_SOURCE_REVISION
        ),
    )

    if not freshness["valid"]:
        return _refuse(_REASON_SOURCE_REVISION)

    # The anchor MUST be a memory this request truly surfaced. A
    # memory that was merely retrieved, an id that does not exist, an
    # id from another request or another conversation is refused
    # here -- there is no "the id exists, so allow it" fallback.
    if anchor not in _surfaced_memory_ids(flash):
        return _refuse(_REASON_ANCHOR_NOT_SURFACED)

    recall_request = {
        "version": _VERSION,
        "mode": _MODE,
        "conversation_id": conversation_id,
        "cognitive_request_id":
            cognitive_request_id,
        "anchor_memory_id": anchor,
        "source_flash_request_id":
            cognitive_request_id,
        "source_flash_unified_revision":
            flash_revision,
        "requested_scope": _ALLOWED_SCOPE,
        "created_at": now_iso(),
    }

    return {
        "valid": True,
        "mode": _MODE,
        "reason": None,
        "recall_request": recall_request,
        "flash": flash,
    }


# ------------------------------------------------------
# Recall Request persistence (request event, not a load)
# ------------------------------------------------------


def is_valid_recall_request_artifact(
    artifact: Any,
    *,
    conversation_id: Any = None,
    cognitive_request_id: Any = None,
) -> bool:
    """Structural identity of one persisted Recall Request event.

    A path being correct never implies its content is correct, so
    every reader re-validates:

      - the contract, the mode, the request identity, the anchor, the
        scope and the Flash revision binding (``_valid_recall_request_core``);
      - ``source_flash_request_id``, which must bind to this request
        (the v1 Flash is request scoped);
      - ``status``, which may only be ``requested`` -- a Recall Request
        records a request, never a load state;
      - ``request_fingerprint``, which is RECOMPUTED from the
        artifact's own identity and compared. The fingerprint an
        artifact carries about itself is never trusted.
    """

    if not _valid_recall_request_core(
        artifact,
        conversation_id=conversation_id,
        cognitive_request_id=(
            cognitive_request_id
        ),
    ):
        return False

    if not is_valid_recall_id(
        artifact.get("recall_id")
    ):
        return False

    if (
        artifact.get("status")
        != _STATUS_REQUESTED
    ):
        return False

    fingerprint = artifact.get(
        "request_fingerprint"
    )

    if not is_valid_fingerprint(fingerprint):
        return False

    expected = recall_request_fingerprint(
        conversation_id=artifact[
            "conversation_id"
        ],
        cognitive_request_id=artifact[
            "cognitive_request_id"
        ],
        anchor_memory_id=artifact[
            "anchor_memory_id"
        ],
        requested_scope=artifact[
            "requested_scope"
        ],
    )

    return fingerprint == expected


def _valid_recall_request_core(
    artifact: Any,
    *,
    conversation_id: Any = None,
    cognitive_request_id: Any = None,
) -> bool:
    """The identity shared by an authorized request and its persisted
    event: contract, mode, request identity, anchor, scope, revision."""

    if not isinstance(artifact, dict):
        return False

    if (
        artifact.get("version") != _VERSION
        or artifact.get("mode") != _MODE
    ):
        return False

    artifact_conversation = artifact.get(
        "conversation_id"
    )

    artifact_request = artifact.get(
        "cognitive_request_id"
    )

    if (
        conversation_id is not None
        and artifact_conversation
        != conversation_id
    ):
        return False

    if (
        cognitive_request_id is not None
        and artifact_request
        != cognitive_request_id
    ):
        return False

    if (
        not is_valid_conversation_id(
            artifact_conversation
        )
        or not is_valid_cognitive_request_id(
            artifact_request
        )
    ):
        return False

    anchor = artifact.get("anchor_memory_id")

    if (
        not isinstance(anchor, str)
        or not anchor.strip()
    ):
        return False

    if (
        artifact.get("requested_scope")
        != _ALLOWED_SCOPE
    ):
        return False

    # The v1 Flash is request scoped, so the Flash a Recall Request was
    # authorized against must be THIS request's Flash.
    if (
        artifact.get("source_flash_request_id")
        != artifact_request
    ):
        return False

    return is_valid_revision(
        artifact.get(
            "source_flash_unified_revision"
        )
    )


def find_recall_request_by_fingerprint(
    *,
    conversation_id: Any,
    cognitive_request_id: Any,
    fingerprint: Any,
) -> dict[str, Any] | None:
    """The persisted Recall Request for one deterministic fingerprint.

    A corrupt artifact (wrong identity, wrong contract, malformed
    fingerprint) is ignored, never returned as a duplicate success.
    """

    if (
        not is_valid_conversation_id(conversation_id)
        or not is_valid_cognitive_request_id(
            cognitive_request_id
        )
    ):
        return None

    if (
        not isinstance(fingerprint, str)
        or not fingerprint
    ):
        return None

    try:
        directory = recall_request_dir(
            conversation_id,
            cognitive_request_id,
        )
    except ValueError:
        return None

    if not directory.is_dir():
        return None

    for path in sorted(
        directory.glob("recall_*.json")
    ):
        artifact = read_json(path)

        if not is_valid_recall_request_artifact(
            artifact,
            conversation_id=conversation_id,
            cognitive_request_id=(
                cognitive_request_id
            ),
        ):
            continue

        if (
            artifact.get("request_fingerprint")
            == fingerprint
        ):
            return artifact

    return None


def read_recall_request(
    *,
    conversation_id: Any,
    cognitive_request_id: Any,
    recall_id: Any,
) -> dict[str, Any] | None:
    """Read one Recall Request event, identity-validated."""

    if (
        not is_valid_conversation_id(conversation_id)
        or not is_valid_cognitive_request_id(
            cognitive_request_id
        )
        or not is_valid_recall_id(recall_id)
    ):
        return None

    artifact = read_json(
        recall_request_path(
            conversation_id,
            cognitive_request_id,
            recall_id,
        )
    )

    if not is_valid_recall_request_artifact(
        artifact,
        conversation_id=conversation_id,
        cognitive_request_id=(
            cognitive_request_id
        ),
    ):
        return None

    if artifact.get("recall_id") != recall_id:
        return None

    return artifact


def record_recall_request(
    *,
    recall_request: Any,
    recall_id: Any,
) -> dict[str, Any]:
    """Persist one explicit Recall Request event. Idempotent.

    This is what makes ``recall_requested`` independent of whether the
    memories can later be loaded: it is written from the authorized
    request alone, BEFORE any anchor load is attempted, so an anchor
    that was deleted in the meantime still leaves a real
    ``recall_requested`` record.

    The fingerprint (conversation + request + anchor + scope) decides
    identity: a retried request with the same fingerprint reuses the
    already-persisted recall id and never creates a second event.
    """

    if not _valid_recall_request_core(
        recall_request
    ):
        return {
            "stored": False,
            "mode": _MODE,
            "decision": "no_record",
            "reason": "invalid_recall_request",
            "duplicate": False,
            "recall_id": None,
            "recall_request": None,
        }

    if not is_valid_recall_id(recall_id):
        return {
            "stored": False,
            "mode": _MODE,
            "decision": "no_record",
            "reason": "invalid_recall_id",
            "duplicate": False,
            "recall_id": None,
            "recall_request": None,
        }

    conversation_id = recall_request[
        "conversation_id"
    ]

    cognitive_request_id = recall_request[
        "cognitive_request_id"
    ]

    fingerprint = recall_request_fingerprint(
        conversation_id=conversation_id,
        cognitive_request_id=(
            cognitive_request_id
        ),
        anchor_memory_id=recall_request[
            "anchor_memory_id"
        ],
        requested_scope=recall_request[
            "requested_scope"
        ],
    )

    with LOCK:
        existing = (
            find_recall_request_by_fingerprint(
                conversation_id=(
                    conversation_id
                ),
                cognitive_request_id=(
                    cognitive_request_id
                ),
                fingerprint=fingerprint,
            )
        )

        if isinstance(existing, dict):
            return {
                "stored": True,
                "mode": _MODE,
                "decision": "recorded",
                "reason":
                    "duplicate_recall_request",
                "duplicate": True,
                "recall_id": existing.get(
                    "recall_id"
                ),
                "recall_request": existing,
            }

        artifact = {
            "version": _VERSION,
            "mode": _MODE,
            "conversation_id": conversation_id,
            "cognitive_request_id":
                cognitive_request_id,
            "recall_id": recall_id,
            "anchor_memory_id":
                recall_request[
                    "anchor_memory_id"
                ],
            "source_flash_request_id":
                recall_request.get(
                    "source_flash_request_id"
                ),
            "source_flash_unified_revision":
                recall_request.get(
                    "source_flash_unified_revision"
                ),
            "requested_scope":
                recall_request[
                    "requested_scope"
                ],
            "request_fingerprint":
                fingerprint,
            "created_at": now_iso(),
            "status": _STATUS_REQUESTED,
        }

        atomic_write(
            recall_request_path(
                conversation_id,
                cognitive_request_id,
                recall_id,
            ),
            artifact,
        )

    return {
        "stored": True,
        "mode": _MODE,
        "decision": "recorded",
        "reason": "recall_request_recorded",
        "duplicate": False,
        "recall_id": recall_id,
        "recall_request": artifact,
    }


def recall_request_status(
    *,
    conversation_id: Any,
    cognitive_request_id: Any,
    recall_id: Any,
) -> dict[str, Any]:
    """Privacy-safe status of one Recall Request event."""

    artifact = read_recall_request(
        conversation_id=conversation_id,
        cognitive_request_id=(
            cognitive_request_id
        ),
        recall_id=recall_id,
    )

    if not isinstance(artifact, dict):
        return {"exists": False}

    return {
        "exists": True,
        "version": artifact.get("version"),
        "mode": artifact.get("mode"),
        "status": artifact.get("status"),
        "requested_scope":
            artifact.get("requested_scope"),
        "source_flash_unified_revision":
            artifact.get(
                "source_flash_unified_revision"
            ),
    }