from __future__ import annotations


_OPERIT_EXTRA_ID_PREFIX = (
    "message_insert_extra_bundle_"
)

_LEGACY_EXTRA_ID_PREFIXES = (
    "message_insert_extra_time_",
    "message_insert_extra_battery_",
    "message_insert_extra_weather_",
    "message_insert_extra_location_",
    "message_insert_extra_notifications_",
)


def is_confirmed_dynamic_attachment(
    attrs: dict[str, str],
) -> bool:
    """
    Destructive ownership predicate.

    Filename alone is deliberately insufficient.

    Only attachment IDs documented/generated by Operit's
    message_insert package may be removed.
    """

    attachment_id = attrs.get("id", "")

    if attachment_id.startswith(
        _OPERIT_EXTRA_ID_PREFIX
    ):
        return True

    return any(
        attachment_id.startswith(prefix)
        for prefix in _LEGACY_EXTRA_ID_PREFIXES
    )


def fingertips_signature(
    attrs: dict[str, str],
) -> dict[str, bool]:
    """
    Privacy-safe metadata shape only.

    No raw id or filename is returned.
    """

    attachment_id = attrs.get("id", "")
    filename = attrs.get("filename", "")

    aid = attachment_id.lower()
    fn = filename.lower()

    return {
        "id_present": bool(attachment_id),
        "filename_present": bool(filename),
        "id_starts_fingertips": (
            aid.startswith("fingertips")
        ),
        "id_contains_fingertips": (
            "fingertips" in aid
        ),
        "filename_exact_fingertips_txt": (
            fn == "fingertips.txt"
        ),
        "filename_starts_fingertips": (
            fn.startswith("fingertips")
        ),
        "id_contains_zhijin": (
            "指尖" in attachment_id
        ),
        "filename_contains_zhijin": (
            "指尖" in filename
        ),
    }
